[vpn_lab_nodes]
lab-vpn-01 ansible_host=127.0.0.1 ansible_connection=local

[vpn_lab_nodes:vars]
agent_node_id=1
agent_node_code=LAB-SG-01
agent_wg_iface=wg0
agent_wg_port=51820
agent_wan_iface=eth0
agent_authorized_pools="10.200.20.0/24"
agent_http_addr="127.0.0.1:8082"
agent_version="1.0.0"
